export type IProduct = {
  id: number;
  title: string;
  category: string;
  thumbnail: string;
  application: string;
  prefabrication: string;
  customization: string;
  sizes: string;
  thickness: string;
  finish: string;
  image: string;
};

export const products: IProduct[] = [
  {
    id: 1,
    title: "Crystal OFF White",
    category: "BASIC SERIES",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    thumbnail: "/1-OFFWhite.png",
    image: "/OFFWhite-1.png",
  },
  {
    id: 2,
    title: "Crystal Bright White",
    category: "BASIC SERIES",
    thumbnail: "/2-CrystalWhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/2-CrystalBrightWhite.png",
  },
  {
    id: 3,
    title: "Crystal Blue",
    category: "BASIC SERIES",
    thumbnail: "/3-CrystalBlue.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/3--CrystalBlue.png",
  },
  {
    id: 4,
    title: "Crystal Red",
    category: "BASIC SERIES",
    thumbnail: "/4B-CrystalRed.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/4-CrystalRed.png",
  },
  {
    id: 5,
    title: "Crystal Grey",
    category: "BASIC SERIES",
    thumbnail: "/5CrystalGrey.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/5Crystal-Grey.png",
  },
  {
    id: 6,
    title: "Grainy Dark Grey",
    category: "BASIC SERIES",
    thumbnail: "/6GrainyDarkGrey.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/6-GrainyDarkGrey.png",
  },
  {
    id: 7,
    title: "Grainy White",
    category: "BASIC SERIES",
    thumbnail: "/7-Grainywhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/7Grainywhite.png",
  },
  {
    id: 8,
    title: "Grainy Brown",
    category: "BASIC SERIES",
    thumbnail: "/8-GrainyBrown.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/8GrainyBrown.png",
  },
  {
    id: 9,
    title: "Grainy Iron",
    category: "BASIC SERIES",
    thumbnail: "/9-GrainyIron.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/9GrainyIron.png",
  },
  {
    id: 10,
    title: "Grainy Black",
    category: "BASIC SERIES",
    thumbnail: "/10-GrainyBlack.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/10GrainyBlack.png",
  },
  {
    id: 11,
    title: "Alaska White",
    category: "CALACATTA SERIES",
    thumbnail: "/1-Alaskawhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/1AlaskaWhite.png",
  },
  {
    id: 12,
    title: "Calacatta Alexa",
    category: "CALACATTA SERIES",
    thumbnail: "/2-CalacattaAlexa.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/2CalacattaAlexa.png",
  },
  {
    id: 13,
    title: "Calacatta Classic",
    category: "CALACATTA SERIES",
    thumbnail: "/3-Calacattaclassic.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/3Calacattaclassic.png",
  },
  {
    id: 14,
    title: "Calacatta Dally",
    category: "CALACATTA SERIES",
    thumbnail: "/4-CalacattaDally.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/4CalacattaDally.png",
  },
  {
    id: 15,
    title: "Calacatta Gold",
    category: "CALACATTA SERIES",
    thumbnail: "/5-CalacattaGold.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/5CalacattaGold.png",
  },
  {
    id: 16,
    title: "Calacatta Scott",
    category: "CALACATTA SERIES",
    thumbnail: "/6-CalacattaScott.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/6CalacattaScott.png",
  },
  {
    id: 17,
    title: "Calacatta Spider",
    category: "CALACATTA SERIES",
    thumbnail: "/7-CalacattaSpider.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/7CalacattaSpider.png",
  },
  {
    id: 18,
    title: "Exotic White",
    category: "CALACATTA SERIES",
    thumbnail: "/8-Exoticwhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/8Exoticwhite.png",
  },
  {
    id: 19,
    title: "Imperial White",
    category: "CALACATTA SERIES",
    thumbnail: "/9-Imperialwhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/9Imperialwhite.png",
  },
  {
    id: 20,
    title: "Olympia White",
    category: "CALACATTA SERIES",
    thumbnail: "/10-Olympiawhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/10Olympiawhite.png",
  },
  {
    id: 21,
    title: "Carrara Beige",
    category: "CARRARA SERIES",
    thumbnail: "/1-CarraraBeige.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/1CarraraBeige.png",
  },
  {
    id: 22,
    title: "Carrara Grey",
    category: "CARRARA SERIES",
    thumbnail: "/2-Carraragrey.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/2Carraragrey.png",
  },
  {
    id: 23,
    title: "Carrara White",
    category: "CARRARA SERIES",
    thumbnail: "/3-CarraraWhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/3CarraraDark.png",
  },
  {
    id: 24,
    title: "Carrara Bianco",
    category: "CARRARA SERIES",
    thumbnail: "/4-CarraraBianco.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/4CarraraBianco.png",
  },
  {
    id: 25,
    title: "Carrara Gold",
    category: "CARRARA SERIES",
    thumbnail: "/5-CarraraGold.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/5CarraraGold.png",
  },
  {
    id: 26,
    title: "Avalanche",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/1-Avalanche.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/1Avalanche.png",
  },
  {
    id: 27,
    title: "Bellingham",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/2-Bellingham.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/2Bellingham.png",
  },
  {
    id: 28,
    title: "Black Spider",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/3-BlackSpider.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/3BlackSpider.png",
  },
  {
    id: 29,
    title: "Canterbury",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/4-Canterbury.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/4Canterbury.png",
  },
  {
    id: 30,
    title: "Grainy Black",
    category: "BASIC SERIES",
    thumbnail: "/5-JeliskaWhite.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/5JeliskaWhite.png",
  },
  {
    id: 31,
    title: "Vanilla Black",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/6-VanilaBlack.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/6VanilaBlack.png",
  },
  {
    id: 32,
    title: "Rain Forest",
    category: "MULTI EXOTIC SERIES",
    thumbnail: "/7-RainForest.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/7RainForest.png",
  },
  {
    id: 33,
    title: "Grainy Black",
    category: "BASIC SERIES",
    thumbnail: "/8-Oxford.png",
    sizes: "1650 x 3250 mm & 1500 x 3100 mm",
    thickness: "2 & 3 cm",
    finish: "Polished, honed, leathered",
    customization: "Available",
    prefabrication: "Available",
    application: "Countertops, backsplashes, wall cladding, flooring",
    image: "/8Oxford.png",
  },
];
